#pragma once

#include "KPadController.hpp"

namespace System {

// KPadAI: AI-controlled pad input state, extends KPad with AI stick data
// Used to provide synthesized input from the AI system
// @size 0x3C0 (KPad base + AI-specific fields)
struct KPadAI: public KPad {
    // @addr 0x80525988
    KPadAI();

    // Copy the AI-generated race input state into the KPad's internal state.
    // The race input contains stick, trick, drift, and acceleration data
    // synthesized by the AI engine's control system.
    // This is called each frame before the kart processes input.
    // @addr 0x80523E94
    void setInputState(KPadRaceInputState* inputState);

    // Get the generated AI input state.
    // Returns a pointer to the internally stored AI input that was last
    // set via setInputState or generated by the AI engine.
    // @addr 0x80523F00
    KPadRaceInputState* getInputState();

    // Reset AI input to neutral (zero stick, no buttons).
    // Called when the AI kart should stop providing input,
    // such as during respawn or race end.
    // @addr 0x80523F20
    void resetInput();

    // Set AI difficulty parameters.
    // Higher difficulty values make the AI more aggressive and accurate.
    //   0 = Easy   - lower top speed, wider turns, more mistakes
    //   1 = Medium - balanced performance (default)
    //   2 = Hard   - near-optimal racing lines, minimal mistakes
    // @addr 0x80523F40
    void setDifficulty(u8 difficulty);

    // Phase 38 additions
    void init(u8 playerIdx);
    void update(u32 frameCount);
    void setSteering(f32 targetX, f32 targetY);
    void setAcceleration(f32 accelValue);
    void setDriftInput(bool shouldDrift);
    void setTrickInput(u8 trickDir);
    void setItemInput(bool useItem);
    void applyDifficultyScaling();
    KPadRaceInputState getInputStateCopy() const;

    // AI skill level (0-2), affects input smoothing and reaction time
    u8 mDifficulty;
    u8 mPlayerIdx;

    // The AI-generated input state, copied each frame from the AI engine
    KPadRaceInputState mAIInput;

    // Phase 38 member variables
    f32 mSteerTargetX;
    f32 mSteerTargetY;
    f32 mAccelTarget;
    bool mDriftTarget;
    u8 mTrickDir;
    bool mItemTarget;
    u32 mReactionTimer;

    // The stick values are stored at offsets relative to the base class
    // that correspond to the u16 zeroing in the constructor:
    // 0xC6, 0xC8 (raw stick X/Y), 0x1B2, 0x1B4 (sub-stick X/Y),
    // 0x29E, 0x2A0 (trigger L/R), 0x38A, 0x38C (additional inputs)
};

// KPadAIController: Manages AI input calculation and dispatch
// Bridges the AI engine output to the KPadRaceInputState
struct KPadAIController {
    // Set up the race input state structure for AI processing.
    // The raceInput is populated with:
    //   - field_0x04: pointer to AI engine data (at offset 0x276C)
    //   - field_0x08: -1 (sentinel, no UI input source)
    //   - field_0x0C: AI controller ID (2 = AI type)
    //   - field_0x00: 0 (no raw pad data)
    // Then calls the AI engine's update to fill in stick/buttons.
    // @addr 0x80526F40
    void calcInner(KPadRaceInputState* raceInput, KPadUIInputState* uiInput);

    // Update all AI pads in the race.
    // Iterates over each AI player slot and calls calcInner for each.
    // The frameCount is used for periodic AI decision updates.
    // @addr 0x80527000
    static void calcAll(u32 frameCount);

    // Create AI pad for a player slot.
    // Allocates a new KPadAI on the heap and initializes it with
    // default difficulty (medium). Returns nullptr on failure.
    // @addr 0x80527100
    static KPadAI* createForPlayer(u8 playerIdx);

    // Destroy AI pad for a player slot.
    // Cleans up the KPadAI instance and nulls the slot pointer.
    // Safe to call even if no AI pad exists for the slot.
    // @addr 0x80527200
    static void destroyForPlayer(u8 playerIdx);
};

} // namespace System