#pragma once
// Mario Kart Wii PC Port - Master Header
// Auto-generated by Phase 5 classification
// Includes all module headers

#include "types.h"

// Game modules
#include "Physics/Physics.h"
#include "KartMovement/KartMovement.h"
#include "Collision/Collision.h"
#include "RaceEngine/RaceEngine.h"
#include "AIRace/AIRace.h"
#include "ItemSystem/ItemSystem.h"
#include "Network/Network.h"
#include "UI/UI.h"
#include "Audio/Audio.h"
#include "Rendering/Rendering.h"
#include "Scene/Scene.h"

// Runtime / Platform
#include "Runtime/Runtime.h"

// Data / Static
#include "Data/Data.h"

// mkwii namespace forward declarations
namespace mkwii {
    // Core game classes
    class Racedata;
    class Raceinfo;
    class RaceConfig;
    class Player;
    class KartMove;
    class KartDynamics;
    class KartBody;
    class KartPhysics;
    class ItemHolder;
    class ItemObj;
    class AI;
    class AIControl;
} // namespace mkwii
