#pragma once
// KartMovement module - Mario Kart Wii PC Port
// Auto-generated by Phase 5 classification
// Contains 268 decompiled functions

#include "../types.h"

// 0x8058a80c (certain)
// PlayerSub10Bike_getWheelieSoftSpeedLimitBonus

