#pragma once
// RaceEngine module - Mario Kart Wii PC Port
// Auto-generated by Phase 5 classification
// Contains 168 decompiled functions

#include "../types.h"

// 0x80531210 (certain)
// RaceConfig8ScenarioFPQ36System10RaceConfig8Scenario::postInitControllers

// 0x8053569c (certain)
// RaceInfo_update

