#pragma once
// AIRace module - Mario Kart Wii PC Port
// Auto-generated by Phase 5 classification
// Contains 336 decompiled functions

#include "../types.h"

// 0x8072c704 (certain)
// AIControlBaseFv::initAfterManager

